key_map = [
    {"dec": 0, "hex": False, "desc": "Reserved (no event indicated)", "at101": "", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 1, "hex": True, "desc": "Keyboard ErrorRollOver", "at101": "", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 2, "hex": "2", "desc": "Keyboard POSTFail", "at101": "", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 3, "hex": "3", "desc": "Keyboard ErrorUndefined", "at101": "", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 4, "hex": "4", "desc": "Keyboard a and A", "at101": "31", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 5, "hex": "5", "desc": "Keyboard b and B", "at101": "50", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 6, "hex": "6", "desc": "Keyboard c and C", "at101": "48", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 7, "hex": "7", "desc": "Keyboard d and D", "at101": "33", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 8, "hex": "8", "desc": "Keyboard e and E", "at101": "19", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 9, "hex": "9", "desc": "Keyboard f and F", "at101": "34", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 10, "hex": "0A", "desc": "Keyboard g and G", "at101": "35", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 11, "hex": "0B", "desc": "Keyboard h and H", "at101": "36", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 12, "hex": "0C", "desc": "Keyboard i and I", "at101": "24", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 13, "hex": "0D", "desc": "Keyboard j and J", "at101": "37", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 14, "hex": "0E", "desc": "Keyboard k and K", "at101": "38", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 15, "hex": "0F", "desc": "Keyboard l and L", "at101": "39", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 16, "hex": "10", "desc": "Keyboard m and M", "at101": "52", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 17, "hex": "11", "desc": "Keyboard n and N", "at101": "51", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 18, "hex": "12", "desc": "Keyboard o and O", "at101": "25", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 19, "hex": "13", "desc": "Keyboard p and P", "at101": "26", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 20, "hex": "14", "desc": "Keyboard q and Q", "at101": "17", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 21, "hex": "15", "desc": "Keyboard r and R", "at101": "20", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 22, "hex": "16", "desc": "Keyboard s and S", "at101": "32", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 23, "hex": "17", "desc": "Keyboard t and T", "at101": "21", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 24, "hex": "18", "desc": "Keyboard u and U", "at101": "23", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 25, "hex": "19", "desc": "Keyboard v and V", "at101": "49", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 26, "hex": "1A", "desc": "Keyboard w and W", "at101": "18", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 27, "hex": "1B", "desc": "Keyboard x and X", "at101": "47", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 28, "hex": "1C", "desc": "Keyboard y and Y", "at101": "22", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 29, "hex": "1D", "desc": "Keyboard z and Z", "at101": "46", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 30, "hex": "1E", "desc": "Keyboard 1 and !", "at101": "2", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 31, "hex": "1F", "desc": "Keyboard 2 and @", "at101": "3", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 32, "hex": "20", "desc": "Keyboard 3 and #", "at101": "4", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 33, "hex": "21", "desc": "Keyboard 4 and $", "at101": "5", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 34, "hex": "22", "desc": "Keyboard 5 and %", "at101": "6", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 35, "hex": "23", "desc": "Keyboard 6 and ^", "at101": "7", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 36, "hex": "24", "desc": "Keyboard 7 and &", "at101": "8", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 37, "hex": "25", "desc": "Keyboard 8 and *", "at101": "9", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 38, "hex": "26", "desc": "Keyboard 9 and (", "at101": "10", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 39, "hex": "27", "desc": "Keyboard 0 and )", "at101": "11", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 40, "hex": "28", "desc": "Keyboard Return (ENTER)", "at101": "43", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 41, "hex": "29", "desc": "Keyboard ESCAPE", "at101": "110", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 42, "hex": "2A", "desc": "Keyboard DELETE (Backspace)", "at101": "15", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 43, "hex": "2B", "desc": "Keyboard Tab", "at101": "16", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 44, "hex": "2C", "desc": "Keyboard Spacebar", "at101": "61", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 45, "hex": "2D", "desc": "Keyboard - and (underscore)", "at101": "12", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 46, "hex": "2E", "desc": "Keyboard = and +", "at101": "13", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 47, "hex": "2F", "desc": "Keyboard [ and {", "at101": "27", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 48, "hex": "30", "desc": "Keyboard ] and }", "at101": "28", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 49, "hex": "31", "desc": "Keyboard \ and |", "at101": "29", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 50, "hex": "32", "desc": "Keyboard Non-US # and ~", "at101": "42", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 51, "hex": "33", "desc": "Keyboard ; and :", "at101": "40", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 52, "hex": "34", "desc": "Keyboard ‘ and “", "at101": "41", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 53, "hex": "35", "desc": "Keyboard Grave Accent and Tilde", "at101": True, "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 54, "hex": "36", "desc": "Keyboard, and <", "at101": "53", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 55, "hex": "37", "desc": "Keyboard . and >", "at101": "54", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 56, "hex": "38", "desc": "Keyboard / and ?", "at101": "55", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 57, "hex": "39", "desc": "Keyboard Caps Lock", "at101": "30", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 58, "hex": "3A", "desc": "Keyboard F1", "at101": "112", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 59, "hex": "3B", "desc": "Keyboard F2", "at101": "113", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 60, "hex": "3C", "desc": "Keyboard F3", "at101": "114", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 61, "hex": "3D", "desc": "Keyboard F4", "at101": "115", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 62, "hex": "3E", "desc": "Keyboard F5", "at101": "116", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 63, "hex": "3F", "desc": "Keyboard F6", "at101": "117", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 64, "hex": "40", "desc": "Keyboard F7", "at101": "118", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 65, "hex": "41", "desc": "Keyboard F8", "at101": "119", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 66, "hex": "42", "desc": "Keyboard F9", "at101": "120", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 67, "hex": "43", "desc": "Keyboard F10", "at101": "121", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 68, "hex": "44", "desc": "Keyboard F11", "at101": "122", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 69, "hex": "45", "desc": "Keyboard F12", "at101": "123", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 70, "hex": "46", "desc": "Keyboard PrintScreen", "at101": "124", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 71, "hex": "47", "desc": "Keyboard Scroll Lock", "at101": "125", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 72, "hex": "48", "desc": "Keyboard Pause", "at101": "126", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 73, "hex": "49", "desc": "Keyboard Insert", "at101": "75", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 74, "hex": "4A", "desc": "Keyboard Home", "at101": "80", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 75, "hex": "4B", "desc": "Keyboard PageUp", "at101": "85", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 76, "hex": "4C", "desc": "Keyboard Delete Forward", "at101": "76", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 77, "hex": "4D", "desc": "Keyboard End", "at101": "81", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 78, "hex": "4E", "desc": "Keyboard PageDown", "at101": "86", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 79, "hex": "4F", "desc": "Keyboard RightArrow", "at101": "89", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 80, "hex": "50", "desc": "Keyboard LeftArrow", "at101": "79", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 81, "hex": "51", "desc": "Keyboard DownArrow", "at101": "84", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 82, "hex": "52", "desc": "Keyboard UpArrow", "at101": "83", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 83, "hex": "53", "desc": "Keypad Num Lock and Clear", "at101": "90", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 84, "hex": "54", "desc": "Keypad /", "at101": "95", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 85, "hex": "55", "desc": "Keypad *", "at101": "100", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 86, "hex": "56", "desc": "Keypad -", "at101": "105", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 87, "hex": "57", "desc": "Keypad +", "at101": "106", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 88, "hex": "58", "desc": "Keypad ENTER5", "at101": "108", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 89, "hex": "59", "desc": "Keypad 1 and End", "at101": "93", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 90, "hex": "5A", "desc": "Keypad 2 and Down Arrow", "at101": "98", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 91, "hex": "5B", "desc": "Keypad 3 and PageDn", "at101": "103", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 92, "hex": "5C", "desc": "Keypad 4 and Left Arrow", "at101": "92", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 93, "hex": "5D", "desc": "Keypad 5", "at101": "97", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 94, "hex": "5E", "desc": "Keypad 6 and Right Arrow", "at101": "102", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 95, "hex": "5F", "desc": "Keypad 7 and Home", "at101": "91", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 96, "hex": "60", "desc": "Keypad 8 and Up Arrow", "at101": "96", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 97, "hex": "61", "desc": "Keypad 9 and PageUp", "at101": "101", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 98, "hex": "62", "desc": "Keypad 0 and Insert", "at101": "99", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 99, "hex": "63", "desc": "Keypad . and Delete", "at101": "104", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 100, "hex": "64", "desc": "Keyboard Non-US \ and |", "at101": "45", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 101, "hex": "65", "desc": "Keyboard Application", "at101": "129", "pc": True, "mac": False, "uni": True, "boot": "104"},
    {"dec": 102, "hex": "66", "desc": "Keyboard Power", "at101": "", "pc": False, "mac": True, "uni": True, "boot": ""},
    {"dec": 103, "hex": "67", "desc": "Keypad =", "at101": "", "pc": False, "mac": True, "uni": False, "boot": ""},
    {"dec": 104, "hex": "68", "desc": "Keyboard F13", "at101": "", "pc": False, "mac": True, "uni": False, "boot": ""},
    {"dec": 105, "hex": "69", "desc": "Keyboard F14", "at101": "", "pc": False, "mac": True, "uni": False, "boot": ""},
    {"dec": 106, "hex": "6A", "desc": "Keyboard F15", "at101": "", "pc": False, "mac": True, "uni": False, "boot": ""},
    {"dec": 107, "hex": "6B", "desc": "Keyboard F16", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 108, "hex": "6C", "desc": "Keyboard F17", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 109, "hex": "6D", "desc": "Keyboard F18", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 110, "hex": "6E", "desc": "Keyboard F19", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 111, "hex": "6F", "desc": "Keyboard F20", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 112, "hex": "70", "desc": "Keyboard F21", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 113, "hex": "71", "desc": "Keyboard F22", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 114, "hex": "72", "desc": "Keyboard F23", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 115, "hex": "73", "desc": "Keyboard F24", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 116, "hex": "74", "desc": "Keyboard Execute", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 117, "hex": "75", "desc": "Keyboard Help", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 118, "hex": "76", "desc": "Keyboard Menu", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 119, "hex": "77", "desc": "Keyboard Select", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 120, "hex": "78", "desc": "Keyboard Stop", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 121, "hex": "79", "desc": "Keyboard Again", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 122, "hex": "7A", "desc": "Keyboard Undo", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 123, "hex": "7B", "desc": "Keyboard Cut", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 124, "hex": "7C", "desc": "Keyboard Copy", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 125, "hex": "7D", "desc": "Keyboard Paste", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 126, "hex": "7E", "desc": "Keyboard Find", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 127, "hex": "7F", "desc": "Keyboard Mute", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 128, "hex": "80", "desc": "Keyboard Volume Up", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 129, "hex": "81", "desc": "Keyboard Volume Down", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 130, "hex": "82", "desc": "Keyboard Locking Caps Lock", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 131, "hex": "83", "desc": "Keyboard Locking Num Lock", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 132, "hex": "84", "desc": "Keyboard Locking Scroll Lock", "at101": "", "pc": False, "mac": False, "uni": True, "boot": ""},
    {"dec": 133, "hex": "85", "desc": "Keypad Comma", "at101": "107", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 134, "hex": "86", "desc": "Keypad Equal Sign", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 135, "hex": "87", "desc": "Keyboard International1", "at101": "56", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 136, "hex": "88", "desc": "Keyboard International2", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 137, "hex": "89", "desc": "Keyboard International3", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 138, "hex": "8A", "desc": "Keyboard International4", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 139, "hex": "8B", "desc": "Keyboard International5", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 140, "hex": "8C", "desc": "Keyboard International6", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 141, "hex": "8D", "desc": "Keyboard International7", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 142, "hex": "8E", "desc": "Keyboard International8", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 143, "hex": "8F", "desc": "Keyboard International9", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 144, "hex": "90", "desc": "Keyboard LANG1", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 145, "hex": "91", "desc": "Keyboard LANG2", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 146, "hex": "92", "desc": "Keyboard LANG3", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 147, "hex": "93", "desc": "Keyboard LANG4", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 148, "hex": "94", "desc": "Keyboard LANG5", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 149, "hex": "95", "desc": "Keyboard LANG6", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 150, "hex": "96", "desc": "Keyboard LANG7", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 151, "hex": "97", "desc": "Keyboard LANG8", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 152, "hex": "98", "desc": "Keyboard LANG9", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 153, "hex": "99", "desc": "Keyboard Alternate Erase", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 154, "hex": "9A", "desc": "Keyboard SysReq/Attention", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 155, "hex": "9B", "desc": "Keyboard Cancel", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 156, "hex": "9C", "desc": "Keyboard Clear", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 157, "hex": "9D", "desc": "Keyboard Prior", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 158, "hex": "9E", "desc": "Keyboard Return", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 159, "hex": "9F", "desc": "Keyboard Separator", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 160, "hex": "A0", "desc": "Keyboard Out", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 161, "hex": "A1", "desc": "Keyboard Oper", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 162, "hex": "A2", "desc": "Keyboard Clear/Again", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 163, "hex": "A3", "desc": "Keyboard CrSel/Props", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 164, "hex": "A4", "desc": "Keyboard ExSel", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 165, "hex": "A5", "desc": "Reserved", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 166, "hex": "A6", "desc": "Reserved", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 167, "hex": "A7", "desc": "Reserved", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 168, "hex": "A8", "desc": "Reserved", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 169, "hex": "A9", "desc": "Reserved", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 170, "hex": "AA", "desc": "Reserved", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 171, "hex": "AB", "desc": "Reserved", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 172, "hex": "AC", "desc": "Reserved", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 173, "hex": "AD", "desc": "Reserved", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 174, "hex": "AE", "desc": "Reserved", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 175, "hex": "AF", "desc": "Reserved", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 176, "hex": "B0", "desc": "Keypad 00", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 177, "hex": "B1", "desc": "Keypad 000", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 178, "hex": "B2", "desc": "Thousands Separator", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 179, "hex": "B3", "desc": "Decimal Separator", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 180, "hex": "B4", "desc": "Currency Unit", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 181, "hex": "B5", "desc": "Currency Sub-unit", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 182, "hex": "B6", "desc": "Keypad (", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 183, "hex": "B7", "desc": "Keypad )", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 184, "hex": "B8", "desc": "Keypad {", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 185, "hex": "B9", "desc": "Keypad }", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 186, "hex": "BA", "desc": "Keypad Tab", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 187, "hex": "BB", "desc": "Keypad Backspace", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 188, "hex": "BC", "desc": "Keypad A", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 189, "hex": "BD", "desc": "Keypad B", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 190, "hex": "BE", "desc": "Keypad C", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 191, "hex": "BF", "desc": "Keypad D", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 192, "hex": "C0", "desc": "Keypad E", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 193, "hex": "C1", "desc": "Keypad F", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 194, "hex": "C2", "desc": "Keypad XOR", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 195, "hex": "C3", "desc": "Keypad ^", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 196, "hex": "C4", "desc": "Keypad %", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 197, "hex": "C5", "desc": "Keypad <", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 198, "hex": "C6", "desc": "Keypad >", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 199, "hex": "C7", "desc": "Keypad &", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 200, "hex": "C8", "desc": "Keypad &&", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 201, "hex": "C9", "desc": "Keypad |", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 202, "hex": "CA", "desc": "Keypad ||", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 203, "hex": "CB", "desc": "Keypad :", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 204, "hex": "CC", "desc": "Keypad #", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 205, "hex": "CD", "desc": "Keypad Space", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 206, "hex": "CE", "desc": "Keypad @", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 207, "hex": "CF", "desc": "Keypad !", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 208, "hex": "D0", "desc": "Keypad Memory Store", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 209, "hex": "D1", "desc": "Keypad Memory Recall", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 210, "hex": "D2", "desc": "Keypad Memory Clear", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 211, "hex": "D3", "desc": "Keypad Memory Add", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 212, "hex": "D4", "desc": "Keypad Memory Subtract", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 213, "hex": "D5", "desc": "Keypad Memory Multiply", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 214, "hex": "D6", "desc": "Keypad Memory Divide", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 215, "hex": "D7", "desc": "Keypad +/-", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 216, "hex": "D8", "desc": "Keypad Clear", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 217, "hex": "D9", "desc": "Keypad Clear Entry", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 218, "hex": "DA", "desc": "Keypad Binary", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 219, "hex": "DB", "desc": "Keypad Octal", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 220, "hex": "DC", "desc": "Keypad Decimal", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 221, "hex": "DD", "desc": "Keypad Hexadecimal", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 222, "hex": "DE", "desc": "Reserved", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 223, "hex": "DF", "desc": "Reserved", "at101": "", "pc": False, "mac": False, "uni": False, "boot": ""},
    {"dec": 224, "hex": "E0", "desc": "Keyboard LeftControl", "at101": "58", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 225, "hex": "E1", "desc": "Keyboard LeftShift", "at101": "44", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 226, "hex": "E2", "desc": "Keyboard LeftAlt", "at101": "60", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 227, "hex": "E3", "desc": "Keyboard Left GUI", "at101": "127", "pc": True, "mac": True, "uni": True, "boot": "104"},
    {"dec": 228, "hex": "E4", "desc": "Keyboard RightControl", "at101": "64", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 229, "hex": "E5", "desc": "Keyboard RightShift", "at101": "57", "pc": True, "mac": True, "uni": True, "boot": "4/101/104"},
    {"dec": 230, "hex": "E6", "desc": "Keyboard RightAlt", "at101": "62", "pc": True, "mac": True, "uni": True, "boot": "101/104"},
    {"dec": 231, "hex": "E7", "desc": "Keyboard Right GUI", "at101": "128", "pc": True, "mac": True, "uni": True, "boot": "104"},
]